# Schema for the configuration files of the table_task module.
table_task.settings:
  type: config_object
  label: 'table_task settings'
  mapping:
    example:
      type: string
      label: 'Example'
