# Schema for the configuration files of the task_six_dropdown module.
task_six_dropdown.settings:
  type: config_object
  label: 'task_six_dropdown settings'
  mapping:
    example:
      type: string
      label: 'Example'
