<?php

/**
 * @file
 * Primary module hooks for module_custom module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_mail().
 */
function mail_task_four_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'create_page':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['text_area'];
      break;
  }
}

/**
 * Implements hook_entity_insert().
 */
function mail_task_four_entity_insert(EntityInterface $entity) {
  // exit;.
  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'page')) {
    return;
  }

  $mailManager = \Drupal::service('plugin.manager.mail');

  $module = 'mail_task_four';
  $key = 'create_page';
  $to = \Drupal::currentUser()->getEmail();

  $helptext = \Drupal::configFactory()->getEditable("ExampleForm.settings")->get("subject");
  $msg = \Drupal::configFactory()->getEditable("ExampleForm.settings")->get("text_area");

  $token_service = \Drupal::token();

  $sub_message = $token_service->replace($msg, ['node' => $entity], ['clear' => TRUE]);
  $hlp = $token_service->replace($helptext, ['node' => $entity], ['clear' => TRUE]);

  $params['subject'] = $sub_message;
  $params['text_area'] = $hlp;
  // print_r(  $params['body']['value']);.
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = TRUE;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== TRUE) {

    \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent'), 'error');
  }
  else {

    \Drupal::messenger()->addMessage(t('Your message has been sent.'), 'status');
  }
}

/**
 * Implements hook_mail_alter().
 */
function mail_task_four_mail_alter(&$message) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
}
